site_name: Aplicación Innovadora para la Gestión de Agua Rural
site_url: https://celiamf.github.io/aigar-website/

theme:
  name: material
  language: es
  custom_dir: overrides
  logo: assets/images/logo.png
  favicon: assets/images/favicon.ico
  font:
    text: Montserrat
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.tabs.sticky
  palette:
    primary: custom
    accent: custom

nav:
  - Inicio: index.md
  - Qué es AIGAR: about.md
  - Descargas: downloads.md
  - Metodología: methodology.md
  - Estado del proyecto: project.md
  - Contacto: contact.md

copyright: '<a href="https://www.icarto.es" target="_blank">© 2020: iCarto - Innovación, Cooperación, Cartografía y Territorio S.L.</a>'

extra_css:
  - assets/stylesheets/main.css

extra_javascript:
  - assets/javascript/counter.js

plugins:
  - macros:
      include_dir: overrides
      module_name: main
      verbose: true

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
