site_name: Aplicación Innovadora para la Gestión de Agua Rural (AIGAR)
site_url: https://Celiamf.github.io/mkdocs-material-demo/

theme:
  name: material
  custom_dir: overrides
  language: es
  logo: assets/images/logo.png
  favicon: assets/images/favicon.ico
  font:
    text: Montserrat
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.tabs.sticky
  palette:
    primary: custom

nav:
  - Inicio: index.md
  - Qué es AIGAR: about.md
  - Metodología: methodology.md
  - Partes involucradas: parties.md
  - Estado del proyecto: project.md
  - Descargas: downloads.md
  - Contacto: contact.md

copyright: "© 2020: iCarto - Innovación, Cooperación, Cartografía y Territorio S.L."

extra_css:
  - assets/stylesheets/extra.css

extra_javascript:
  - assets/javascript/counter.js

plugins: []

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
